[tool.poetry]
name = "datar"
version = "0.0.0"
description = "Probably the closest port of tidyr, dplyr and tibble in python"
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
pipda = "*"
modkit = "*"
pandas = "^1.2"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
