[tool.poetry]
name = "datar"
version = "0.4.3"
description = "Port of dplyr and other related R packages in python, using pipda."
authors = ["pwwang <pwwang@pwwang.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/pwwang/datar"
repository = "https://github.com/pwwang/datar"

[tool.poetry.dependencies]
python = "^3.7.1" # align with pandas
pipda = "*"
diot = "*"
executing = "*"
varname = "*"
pandas = "^1.2"
scipy = { version = "^1.6", optional = true }
wcwidth = { version = "^0.2", optional = true }

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.mypy]
ignore_missing_imports = true
allow_redefinition = true
disable_error_code = ["attr-defined", "no-redef", "union-attr"]
show_error_codes = true
strict_optional = false

[tool.pytest.ini_options]
addopts = "-vv --cov-config=.coveragerc --cov=datar --cov-report xml:cov.xml --cov-report term-missing"
filterwarnings = [
    "error"
]
console_output_style = "progress"
junit_family = "xunit1"

[tool.black]
line-length = 80
target-version = ['py37', 'py38', 'py39']
include = '\.pyi?$'
