[tool.poetry]
name = "datar"
version = "0.0.5"
description = "Port of dplyr and other related R packages in python, using pipda."
authors = ["pwwang <pwwang@pwwang.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/pwwang/datar"
repository = "https://github.com/pwwang/datar"

[tool.poetry.dependencies]
python = "^3.7.1" # align with pandas
pipda = "*"
modkit = "*"
diot="*"
pandas = "^1.2"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
